# 数据库配置
mysql:
  type: 'mysql'
  username: 'root'
  host: '127.0.0.1'
  password: '123456mysql'
  database: 'nestjs_local'
  port: 3306
  charset: 'utf8mb4'
  multipleStatements: true
  dropSchema: false
  synchronize: true
  supportBigNumbers: true
  bigNumberStrings: true
