# 开发环境配置
app:
  prefix: '/api'
  port: 3033

# 数据库配置
db:
  mysql:
    type: 'mysql'
    username: 'root'
    port: 3306
    charset: 'utf8mb4'
    multipleStatements: true
    dropSchema: false
    synchronize: false
    supportBigNumbers: true
    bigNumberStrings: true
